// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAppAuth = "app_auth"

// AppAuth 业务应用的授权码记录
type AppAuth struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"` // 数据id
	CreateAt     time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                 // 创建时间
	UpdateAt     time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                 // 更新时间
	DeleteAt     time.Time `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                 // 删除时间
	AppID        int64     `gorm:"column:app_id;comment:应用id" json:"app_id"`                       // 应用id
	AccessKey    string    `gorm:"column:access_key;comment:授权码" json:"access_key"`                // 授权码
	KeyExp       time.Time `gorm:"column:key_exp;comment:过期时间" json:"key_exp"`                     // 过期时间
	StartTime    time.Time `gorm:"column:start_time;comment:启动时间" json:"start_time"`               // 启动时间
	RegisterTime time.Time `gorm:"column:register_time;comment:登记时间" json:"register_time"`         // 登记时间
	Contract     string    `gorm:"column:contract;comment:合同地址" json:"contract"`                   // 合同地址
	Remark       string    `gorm:"column:remark;comment:备注" json:"remark"`                         // 备注
}

// TableName AppAuth's table name
func (*AppAuth) TableName() string {
	return TableNameAppAuth
}
