// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDataInfo = "data_info"

// DataInfo 数据是否共享 是否需要审核 数据价值
type DataInfo struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"`   // 数据id
	CreateAt       time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                   // 创建时间
	UpdateAt       time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                   // 更新时间
	DeleteAt       time.Time `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                   // 删除时间
	UseID          int64     `gorm:"column:use_id;comment:用户id" json:"use_id"`                         // 用户id
	DataID         string    `gorm:"column:data_id;comment:数据散列" json:"data_id"`                       // 数据散列
	DataName       string    `gorm:"column:data_name;comment:数据名称" json:"data_name"`                   // 数据名称
	DataDiectoryID int32     `gorm:"column:data_diectory_id;comment:数据目录" json:"data_diectory_id"`     // 数据目录
	DataType       string    `gorm:"column:data_type;comment:1表示文档2表示图片3表示视频4表示关系数据" json:"data_type"` // 1表示文档2表示图片3表示视频4表示关系数据
	IsOpen         string    `gorm:"column:is_open;comment:1表示开放2表示关闭" json:"is_open"`                 // 1表示开放2表示关闭
	DataSize       int64     `gorm:"column:data_size;comment:数据大小" json:"data_size"`                   // 数据大小
	DataPos        string    `gorm:"column:data_pos;comment:数据位置" json:"data_pos"`                     // 数据位置
	NodeID         string    `gorm:"column:node_id;comment:节点id" json:"node_id"`                       // 节点id
}

// TableName DataInfo's table name
func (*DataInfo) TableName() string {
	return TableNameDataInfo
}
