// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDataSharelog = "data_sharelog"

// DataSharelog 成功共享的信息记录
type DataSharelog struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"` // 数据id
	CreateAt   time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                 // 创建时间
	UpdateAt   time.Time `gorm:"column:update_at;comment:修改时间" json:"update_at"`                 // 修改时间
	DeleteAt   time.Time `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                 // 删除时间
	BuyerName  string    `gorm:"column:buyer_name;comment:买家名字" json:"buyer_name"`               // 买家名字
	SellerName string    `gorm:"column:seller_name;comment:卖家名字" json:"seller_name"`             // 卖家名字
	DataIds    string    `gorm:"column:data_ids;comment:数据集合" json:"data_ids"`                   // 数据集合
	Price      float64   `gorm:"column:price;comment:价格" json:"price"`                           // 价格
	DataName   string    `gorm:"column:data_name;comment:数据名称" json:"data_name"`                 // 数据名称
}

// TableName DataSharelog's table name
func (*DataSharelog) TableName() string {
	return TableNameDataSharelog
}
