// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNodeInfo = "node_info"

// NodeInfo 超级节点的登记信息
type NodeInfo struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"`  // 数据id
	CreateAt       time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                  // 创建时间
	UpdateAt       time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                  // 更新时间
	DeleteAt       time.Time `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                  // 删除时间
	NodeID         string    `gorm:"column:node_id;comment:节点编号" json:"node_id"`                      // 节点编号
	NodeUnit       string    `gorm:"column:node_unit;comment:节点单位" json:"node_unit"`                  // 节点单位
	NodeDeploy     string    `gorm:"column:node_deploy;comment:节点部署地址" json:"node_deploy"`            // 节点部署地址
	NodeOperation  string    `gorm:"column:node_operation;comment:节点运营商" json:"node_operation"`       // 节点运营商
	LoginCode      string    `gorm:"column:login_code;comment:节点登录码" json:"login_code"`               // 节点登录码
	NodePublic     string    `gorm:"column:node_public;comment:节点公钥" json:"node_public"`              // 节点公钥
	NodePublicMd5  string    `gorm:"column:node_public_md5;comment:公钥md5" json:"node_public_md5"`     // 公钥md5
	NodePrivate    string    `gorm:"column:node_private;comment:节点私钥" json:"node_private"`            // 节点私钥
	NodePrivateMd5 string    `gorm:"column:node_private_md5;comment:私钥md5" json:"node_private_md5"`   // 私钥md5
	NodeAlgo       string    `gorm:"column:node_algo;comment:节点公私要生成算法" json:"node_algo"`             // 节点公私要生成算法
	NodeStoreKey   string    `gorm:"column:node_store_key;comment:节点sm2私钥保存算法" json:"node_store_key"` // 节点sm2私钥保存算法
}

// TableName NodeInfo's table name
func (*NodeInfo) TableName() string {
	return TableNameNodeInfo
}
