// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNodeHard = "node_hard"

// NodeHard 超级节点的硬件信息
type NodeHard struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"` // 数据id
	CreateAt    time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                 // 创建时间
	UpdateAt    time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                 // 更新时间
	DeleteAt    time.Time `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                 // 删除时间
	HardID      string    `gorm:"column:hard_id;comment:硬件id" json:"hard_id"`                     // 硬件id
	HardName    string    `gorm:"column:hard_name;comment:硬件名称" json:"hard_name"`                 // 硬件名称
	HardModel   string    `gorm:"column:hard_model;comment:硬件型号" json:"hard_model"`               // 硬件型号
	HardType    string    `gorm:"column:hard_type;comment:硬件类别(机架,存储,GPU,CPU)" json:"hard_type"`  // 硬件类别(机架,存储,GPU,CPU)
	HardBrand   string    `gorm:"column:hard_brand;comment:硬件品牌" json:"hard_brand"`               // 硬件品牌
	HardInstall string    `gorm:"column:hard_install;comment:安装信息" json:"hard_install"`           // 安装信息
	HardParams  string    `gorm:"column:hard_params;comment:硬件参数" json:"hard_params"`             // 硬件参数
	HardExplain string    `gorm:"column:hard_explain;comment:硬件介绍" json:"hard_explain"`           // 硬件介绍
}

// TableName NodeHard's table name
func (*NodeHard) TableName() string {
	return TableNameNodeHard
}
