// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameServiceInfo = "service_info"

// ServiceInfo 服务代理的基本信息,包含程序
type ServiceInfo struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"`    // 数据id
	CreateAt       time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                    // 创建时间
	UpdateAt       time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                    // 更新时间
	DeleteAt       time.Time `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                    // 删除时间
	ServiceName    string    `gorm:"column:service_name;comment:服务名称" json:"service_name"`              // 服务名称
	ServiceExecDir string    `gorm:"column:service_exec_dir;comment:程序运行目录" json:"service_exec_dir"`    // 程序运行目录
	ServiceVersion string    `gorm:"column:service_version;comment:服务版本" json:"service_version"`        // 服务版本
	ServiceType    string    `gorm:"column:service_type;comment:服务类别(1水印 2智能 3数权)" json:"service_type"` // 服务类别(1水印 2智能 3数权)
	Status         string    `gorm:"column:status;comment:1表示正常 2表示异常(不能用)" json:"status"`              // 1表示正常 2表示异常(不能用)
	VisitURL       string    `gorm:"column:visit_url;comment:访问地址" json:"visit_url"`                    // 访问地址
	NodeID         string    `gorm:"column:node_id;comment:节点id" json:"node_id"`                        // 节点id
}

// TableName ServiceInfo's table name
func (*ServiceInfo) TableName() string {
	return TableNameServiceInfo
}
