// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameServiceCfg = "service_cfg"

// ServiceCfg json描述的配置信息
type ServiceCfg struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"` // 数据id
	CreateAt      time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                 // 创建时间
	UpdateAt      time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                 // 更新时间
	DeleteAt      time.Time `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                 // 删除时间
	ServiceID     int64     `gorm:"column:service_id;comment:服务id" json:"service_id"`               // 服务id
	ServiceConfig string    `gorm:"column:service_config;comment:服务代理的配置" json:"service_config"`    // 服务代理的配置
	StartTime     time.Time `gorm:"column:start_time;comment:启动时间" json:"start_time"`               // 启动时间
}

// TableName ServiceCfg's table name
func (*ServiceCfg) TableName() string {
	return TableNameServiceCfg
}
