// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysSoft = "sys_soft"

// SysSoft 软件信息表
type SysSoft struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"` // 数据id
	CreateAt       time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                 // 创建时间
	UpdateAt       time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                 // 更新时间
	DeleteAt       time.Time `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                 // 删除时间
	SoftID         string    `gorm:"column:soft_id;comment:软件id" json:"soft_id"`                     // 软件id
	SoftName       string    `gorm:"column:soft_name;comment:软件名称" json:"soft_name"`                 // 软件名称
	SoftVersion    string    `gorm:"column:soft_version;comment:软件版本" json:"soft_version"`           // 软件版本
	SoftPackageURL string    `gorm:"column:soft_package_url;comment:软件包url" json:"soft_package_url"` // 软件包url
	SoftPackageMd5 string    `gorm:"column:soft_package_md5;comment:软件包md5" json:"soft_package_md5"` // 软件包md5
	UploadUser     string    `gorm:"column:upload_user;comment:上传用户" json:"upload_user"`             // 上传用户
}

// TableName SysSoft's table name
func (*SysSoft) TableName() string {
	return TableNameSysSoft
}
