// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysAuthorityMenu = "sys_authority_menu"

// SysAuthorityMenu 角色菜单绑定表
type SysAuthorityMenu struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"` // 数据id
	CreateAt    time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                 // 创建时间
	UpdateAt    time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                 // 更新时间
	DeleteAt    string    `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                 // 删除时间
	AuthorityID int32     `gorm:"column:authority_id;comment:角色ID" json:"authority_id"`           // 角色ID
	MenuID      int32     `gorm:"column:menu_id;comment:菜单ID" json:"menu_id"`                     // 菜单ID
}

// TableName SysAuthorityMenu's table name
func (*SysAuthorityMenu) TableName() string {
	return TableNameSysAuthorityMenu
}
