// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysOperlog = "sys_operlog"

// SysOperlog 管理端人员的操作记录
type SysOperlog struct {
	ID       int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"` // 数据id
	CreateAt time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                 // 创建时间
	UpdateAt time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                 // 更新时间
	DeleteAt time.Time `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                 // 删除时间
	IP       string    `gorm:"column:ip;comment:请求ip" json:"ip"`                               // 请求ip
	Method   string    `gorm:"column:method;comment:请求方法" json:"method"`                       // 请求方法
	Path     string    `gorm:"column:path;comment:请求路径" json:"path"`                           // 请求路径
	Agent    string    `gorm:"column:agent;comment:请求代理" json:"agent"`                         // 请求代理
	ErrMsg   string    `gorm:"column:err_msg;comment:错误信息" json:"err_msg"`                     // 错误信息
	Body     string    `gorm:"column:body;comment:请求body" json:"body"`                         // 请求body
	Resp     string    `gorm:"column:resp;comment:响应body" json:"resp"`                         // 响应body
	UserID   int64     `gorm:"column:user_id;comment:用户id" json:"user_id"`                     // 用户id
}

// TableName SysOperlog's table name
func (*SysOperlog) TableName() string {
	return TableNameSysOperlog
}
