// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysUser = "sys_user"

// SysUser 系统用户
type SysUser struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"` // 数据id
	CreateAt    time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                 // 创建时间
	UpdateAt    time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                 // 更新时间
	DeleteAt    time.Time `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                 // 删除时间
	Username    string    `gorm:"column:username;comment:用户名称" json:"username"`                   // 用户名称
	Password    string    `gorm:"column:password;comment:用户密码" json:"password"`                   // 用户密码
	Nickname    string    `gorm:"column:nickname;comment:用户 昵称" json:"nickname"`                  // 用户 昵称
	SideMode    string    `gorm:"column:side_mode;comment:用户侧边主题" json:"side_mode"`               // 用户侧边主题
	HeaderImg   string    `gorm:"column:header_img;comment:用户头像" json:"header_img"`               // 用户头像
	BaseColor   string    `gorm:"column:base_color;comment:基础颜色" json:"base_color"`               // 基础颜色
	AuthorityID int64     `gorm:"column:authority_id;comment:用户角色id" json:"authority_id"`         // 用户角色id
	Phone       string    `gorm:"column:phone;comment:电话号码" json:"phone"`                         // 电话号码
	Email       string    `gorm:"column:email;comment:邮箱" json:"email"`                           // 邮箱
	Enable      string    `gorm:"column:enable;comment:1正常 2禁用" json:"enable"`                    // 1正常 2禁用
}

// TableName SysUser's table name
func (*SysUser) TableName() string {
	return TableNameSysUser
}
