// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserBank = "user_bank"

// UserBank 用户用于支付信息表
type UserBank struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"` // 数据id
	CreateAt     time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                 // 创建时间
	UpdateAt     time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                 // 更新时间
	DeleteAt     time.Time `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                 // 删除时间
	UserID       int64     `gorm:"column:user_id;comment:用户id" json:"user_id"`                     // 用户id
	UserBankName string    `gorm:"column:user_bank_name;comment:开户行名称" json:"user_bank_name"`      // 开户行名称
	UserBank     string    `gorm:"column:user_bank;comment:银行卡号" json:"user_bank"`                 // 银行卡号
	Status       string    `gorm:"column:status;comment:1审核通过 0未审核" json:"status"`                 // 1审核通过 0未审核
}

// TableName UserBank's table name
func (*UserBank) TableName() string {
	return TableNameUserBank
}
