// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserProve = "user_prove"

// UserProve 用户认证信息
type UserProve struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"` // 数据id
	CreateAt    time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                 // 创建时间
	UpdateAt    time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                 // 更新时间
	DeleteAt    time.Time `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                 // 删除时间
	UserID      int64     `gorm:"column:user_id;comment:用户id" json:"user_id"`                     // 用户id
	AccountType string    `gorm:"column:account_type;comment:账号类型(qq等da)" json:"account_type"`    // 账号类型(qq等da)
	Account     string    `gorm:"column:account;comment:账号" json:"account"`                       // 账号
	Password    string    `gorm:"column:password;comment:账号密码" json:"password"`                   // 账号密码
	AppID       int64     `gorm:"column:app_id;comment:应用id" json:"app_id"`                       // 应用id
}

// TableName UserProve's table name
func (*UserProve) TableName() string {
	return TableNameUserProve
}
