db:
  host: "192.168.1.149"
  name: "nwyl"
  port: 3306
  user: "root"
  password: "root"
  maximum-pool-size: 20
  maximum-idle-size: 5
jwt:
  exp: 90
  iss: "cored"
  sub: "cored"
  secret: "cored"
cache:
  expire: 3
  use_ssl: false
  access_id: "minio_admin"
  end_point: "10.10.1.40:9000"
  secret_accessKey: "9ijnBHU*@123"
store:
  expire: 3
  use_ssl: false
  access_id: "minio_admin"
  end_point: "10.10.1.40:9000"
  default_size: 500
  secret_accessKey: "9ijnBHU*@123"
backup:
  addr: "http://10.10.254.13:5001"
logging:
  file: "logs/cored.log"
  level: "debug"
  max_age: 30
  max_size: 10
  max_backups: 5
ws:
  listen_address: 
dr:
  del-data: "delData"
  encrypt: "encrypt"
  endpoint: "https://sqwalletapi.smartdatachain.com"
  upload-data: "uploadData"
  dr-user-create: "drUserCreate"
  dr-user-modify: "drUserModify"
  dr-account-info: "drAccountInfo"
  dr-account-sync: "drAccountSync"
  get-dr-user-info: "getDrUserInfo"
  authentication: "authentication"
  select-upload-data: "selectUploadData"
api:
  key-file: "x"
  cert_file: ''
  enable-tls: false
  listen-address: "0.0.0.0:8080"
water:
  grid: "security/grid"
  first: "security/l1"
  plain: "security/plain"
  third: "security/l3"
  protocol: "http"
  end_point: "123.60.56.112:9001"
  generate-stamps: "stamp/circle/create"
  stamp-circle-extract: "stamp/circle/extract"
  stamp-elipse-extract: "stamp/elipse/extract"
  generate-stamp-elipse: "stamp/elipse/create"
  generate-bs-water-mark: "screenBS"
  weak-water-mark-insert: "weak"
  weak-water-mark-extract: "weak/extract"
  electronic-watermark-bright: "flow/plain"
  electronic-watermark-underflow: "flow"
  electronic-watermark-underflow-extract: "flow/extract"
manage:
  listen-addr: "0.0.0.0"
  listen-port: 6000
node:
  node-number: "xxx"
  node-unit: "xxx"
  node-deploy: "xxx"
  node-oper: "xxx"
  node-login-code: "xxx"
  node-public-md5: ""
  node-private-md5: ""
  node-algo: "rsa"
  node-store-key: "1111111111111111"
  node-platform: "ws://0.0.0.0:8083/api/v1/1"
waterx:
  name: "watermark_service.exe"
  args: ":9090 ./exe/config.json"
