
db:
  host: "10.10.254.13"
  name: "nwyl"
  port: 3307
  user: "root"
  password: "9ijnBHU*@123"

jwt:
  exp: 90
  iss: "cored"
  sub: "cored"
  secret: "cored"

cache:
  expire: 3
  use_ssl: false
  access_id: "minio_admin"
  end_point: "10.10.1.40:9000"
  secret_accessKey: "9ijnBHU*@123"

store:
  expire: 3
  use_ssl: false
  access_id: "minio_admin"
  end_point: "10.10.1.40:9000"
  default_size: 500
  secret_accessKey: "9ijnBHU*@123"

backup:
  addr: "http://10.10.254.8:5001"

logging:
  file: "logs/cored.log"
  level: "debug"
  max_age: 30
  max_size: 10
  max_backups: 5

dr:
  del-data: "delData"
  encrypt: "encrypt"
  endpoint: "https://sqwalletapi.smartdatachain.com"
  upload-data: "uploadData"
  dr-user-create: "drUserCreate"
  dr-user-modify: "drUserModify"
  dr-account-info: "drAccountInfo"
  dr-account-sync: "drAccountSync"
  get-dr-user-info: "getDrUserInfo"
  authentication: "authentication"
  select-upload-data: "selectUploadData"

api:
  key-file: "x"
  cert_file: ''
  enable-tls: false
  listen-address: 0.0.0.0:8080

ws:
  listen-address: 0.0.0.0:8083

water:
  grid: "security/grid"
  first: "security/l1"
  plain: "security/plain"
  third: "security/l3"
  protocol: "http"
  end_point: "123.60.56.112:9001"
  generate-stamps: "stamp/circle/create"
  stamp-circle-extract: "stamp/circle/extract"
  stamp-elipse-extract: "stamp/elipse/extract"
  generate-stamp-elipse: "stamp/elipse/create"
  generate-bs-water-mark: "screenBS"
  weak-water-mark-insert: "weak"
  weak-water-mark-extract: "weak/extract"
  electronic-watermark-bright: "flow/plain"
  electronic-watermark-underflow: "flow"
  electronic-watermark-underflow-extract: "flow/extract"

manage:
  listen-addr: "0.0.0.0"
  listen-port: 6000

node:
  node-number: "节点编号"
  node-unit: "四川大学"
  node-deploy: "四川大学10516"
  node-oper: "四川大学计算机学院"
  node-login-code: "8888"
  node-public-md5: "节点公钥md5"
  node-private-md5: "节点私钥md5"
  node-algo: "rsa"
  node-store-key: "111111"
  node-platform: 

