// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDataShare = "data_share"

// DataShare 请求共享和审核来自哪个业务应用
type DataShare struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"`       // 数据id
	CreateAt      time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                       // 创建时间
	UpdateTime    time.Time `gorm:"column:update_time;comment:更新时间" json:"update_time"`                   // 更新时间
	DeleteTime    time.Time `gorm:"column:delete_time;comment:删除时间" json:"delete_time"`                   // 删除时间
	BuyerNode     string    `gorm:"column:buyer_node;comment:买家节点" json:"buyer_node"`                     // 买家节点
	SellerNode    string    `gorm:"column:seller_node;comment:卖家节点" json:"seller_node"`                   // 卖家节点
	BuyerID       int64     `gorm:"column:buyer_id;comment:买家id" json:"buyer_id"`                         // 买家id
	SellerID      int64     `gorm:"column:seller_id;comment:卖家id" json:"seller_id"`                       // 卖家id
	TradeID       string    `gorm:"column:trade_id;comment:交易编号" json:"trade_id"`                         // 交易编号
	TradePrice    float64   `gorm:"column:trade_price;comment:交易价格" json:"trade_price"`                   // 交易价格
	SellerApprove string    `gorm:"column:seller_approve;comment:1表示卖家审核 0表示卖家为审核" json:"seller_approve"` // 1表示卖家审核 0表示卖家为审核
	DataID        string    `gorm:"column:data_id;comment:数据id" json:"data_id"`                           // 数据id
}

// TableName DataShare's table name
func (*DataShare) TableName() string {
	return TableNameDataShare
}
