// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDataDirect = "data_direct"

// DataDirect 数据目录
type DataDirect struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"` // 数据id
	CreateAt     time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                 // 创建时间
	UpdateAt     time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                 // 更新时间
	DeleteAt     time.Time `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                 // 删除时间
	DirectID     string    `gorm:"column:direct_id;comment:目录id(00000000进行表示)" json:"direct_id"`   // 目录id(00000000进行表示)
	DirectIDName string    `gorm:"column:direct_id_name;comment:目录名称" json:"direct_id_name"`       // 目录名称
}

// TableName DataDirect's table name
func (*DataDirect) TableName() string {
	return TableNameDataDirect
}
