// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDataSafe = "data_safe"

// DataSafe 记录数据安全相关信息
type DataSafe struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"` // 数据id
	CreateAt  time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                 // 创建时间
	UpdateAt  time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                 // 更新时间
	DeleteAt  time.Time `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                 // 删除时间
	DataID    string    `gorm:"column:data_id;comment:数据id" json:"data_id"`                     // 数据id
	SafeLevel string    `gorm:"column:safe_level;comment:安全登记(1表示确权2授权3密码)" json:"safe_level"`  // 安全登记(1表示确权2授权3密码)
	SafeInfo  string    `gorm:"column:safe_info;comment:授权信息确权信息密码信息" json:"safe_info"`         // 授权信息确权信息密码信息
}

// TableName DataSafe's table name
func (*DataSafe) TableName() string {
	return TableNameDataSafe
}
