// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDataDirect1 = "data_direct1"

// DataDirect1 mapped from table <data_direct1>
type DataDirect1 struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"` // 数据id
	CreateAt      time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                 // 创建时间
	UpdateAt      time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                 // 更新时间
	DeleteAt      time.Time `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                 // 删除时间
	DirectId1     string    `gorm:"column:direct_id1;comment:目录标识" json:"direct_id1"`               // 目录标识
	DirectId1Name string    `gorm:"column:direct_id1_name;comment:目录名称" json:"direct_id1_name"`     // 目录名称
}

// TableName DataDirect1's table name
func (*DataDirect1) TableName() string {
	return TableNameDataDirect1
}
