// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNodeLog = "node_log"

// NodeLog 记录节点的通信记录
type NodeLog struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"` // 数据id
	CreateAt     time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                 // 创建时间
	UpdateAt     time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                 // 更新时间
	DeleteAt     time.Time `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                 // 删除时间
	NodeIDSender string    `gorm:"column:node_id_sender;comment:发送的节点id" json:"node_id_sender"`    // 发送的节点id
	NodeIDReader string    `gorm:"column:node_id_reader;comment:接受的节点id" json:"node_id_reader"`    // 接受的节点id
	MsgBody      string    `gorm:"column:msg_body;comment:消息内容" json:"msg_body"`                   // 消息内容
	ErrMsg       string    `gorm:"column:err_msg;comment:发送消息是否成功" json:"err_msg"`                 // 发送消息是否成功
}

// TableName NodeLog's table name
func (*NodeLog) TableName() string {
	return TableNameNodeLog
}
