// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNodeUser = "node_user"

// NodeUser 超级节点的联系人信息
type NodeUser struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"`       // 数据id
	CreateAt     time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                       // 创建时间
	UpdateAt     time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                       // 更新时间
	DeleteTime   time.Time `gorm:"column:delete_time;comment:删除时间" json:"delete_time"`                   // 删除时间
	NodeID       string    `gorm:"column:node_id;comment:节点id" json:"node_id"`                           // 节点id
	NodeContact  string    `gorm:"column:node_contact;comment:节点联系人" json:"node_contact"`                // 节点联系人
	NodePhone    string    `gorm:"column:node_phone;comment:节点联系人电话" json:"node_phone"`                  // 节点联系人电话
	ContactType  string    `gorm:"column:contact_type;comment:1表示可登录人员 2纯管理人员 3投资人" json:"contact_type"` // 1表示可登录人员 2纯管理人员 3投资人
	UserAccount  string    `gorm:"column:user_account;comment:节点人员账号" json:"user_account"`               // 节点人员账号
	UserPassword string    `gorm:"column:user_password;comment:节点人员密码" json:"user_password"`             // 节点人员密码
	Status       string    `gorm:"column:status;comment:1表示正常 2表示暂停 3表示禁用" json:"status"`                // 1表示正常 2表示暂停 3表示禁用
}

// TableName NodeUser's table name
func (*NodeUser) TableName() string {
	return TableNameNodeUser
}
