// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNodeSoft = "node_soft"

// NodeSoft 超级节点的软件信息
type NodeSoft struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"` // 数据id
	CreateAt     time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                 // 创建时间
	UpdateAt     time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                 // 更新时间
	DeleteAt     time.Time `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                 // 删除时间
	NodeID       string    `gorm:"column:node_id;comment:节点id" json:"node_id"`                     // 节点id
	SoftID       string    `gorm:"column:soft_id;comment:软件id" json:"soft_id"`                     // 软件id
	SoftURL      string    `gorm:"column:soft_url;comment:软件url" json:"soft_url"`                  // 软件url
	SortSize     int64     `gorm:"column:sort_size;comment:软件大小(单位字节)" json:"sort_size"`           // 软件大小(单位字节)
	SoftMd5      string    `gorm:"column:soft_md5;comment:软件md5" json:"soft_md5"`                  // 软件md5
	SoftVersion  string    `gorm:"column:soft_version;comment:软件版本" json:"soft_version"`           // 软件版本
	SoftLanguage string    `gorm:"column:soft_language;comment:软件语言" json:"soft_language"`         // 软件语言
	SoftType     string    `gorm:"column:soft_type;comment:软件类型" json:"soft_type"`                 // 软件类型
	SoftExplain  string    `gorm:"column:soft_explain;comment:软件说明" json:"soft_explain"`           // 软件说明
	DeviceID     string    `gorm:"column:device_id;comment:所在设备id" json:"device_id"`               // 所在设备id
}

// TableName NodeSoft's table name
func (*NodeSoft) TableName() string {
	return TableNameNodeSoft
}
