// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysMenu = "sys_menu"

// SysMenu 角色菜单
type SysMenu struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"` // 数据id
	CreateAt  time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                 // 创建时间
	UpdateAt  time.Time `gorm:"column:update_at;comment:创建时间" json:"update_at"`                 // 创建时间
	DeleteAt  time.Time `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                 // 删除时间
	MenuLevel int32     `gorm:"column:menu_level;comment:菜单级别" json:"menu_level"`               // 菜单级别
	ParentID  int64     `gorm:"column:parent_id;comment:父菜单ID" json:"parent_id"`                // 父菜单ID
	Path      string    `gorm:"column:path;comment:路由path" json:"path"`                         // 路由path
	Name      string    `gorm:"column:name;comment:路由名称" json:"name"`                           // 路由名称
	Hidden    bool      `gorm:"column:hidden;comment:是否隐藏" json:"hidden"`                       // 是否隐藏
	Compoment string    `gorm:"column:compoment;comment:组件" json:"compoment"`                   // 组件
	Sort      int64     `gorm:"column:sort;comment:排序" json:"sort"`                             // 排序
	Icon      string    `gorm:"column:icon;comment:图标" json:"icon"`                             // 图标
	Title     string    `gorm:"column:title;comment:标题" json:"title"`                           // 标题
}

// TableName SysMenu's table name
func (*SysMenu) TableName() string {
	return TableNameSysMenu
}
