// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysMsg = "sys_msg"

// SysMsg 通知各种信息，有短信和平台通知两种
type SysMsg struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"` // 数据id
	CreateTime time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`             // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;comment:更新时间" json:"update_time"`             // 更新时间
	DeleteTime time.Time `gorm:"column:delete_time;comment:删除时间" json:"delete_time"`             // 删除时间
	MsgType    string    `gorm:"column:msg_type;comment:1表示平台通知 2表示电话通知" json:"msg_type"`        // 1表示平台通知 2表示电话通知
	MsgBody    string    `gorm:"column:msg_body;comment:通知内容" json:"msg_body"`                   // 通知内容
}

// TableName SysMsg's table name
func (*SysMsg) TableName() string {
	return TableNameSysMsg
}
