// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysConfig = "sys_config"

// SysConfig 主要配置通信
type SysConfig struct {
	ID       int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"` // 数据id
	CreateAt time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                 // 创建时间
	UpdateAt time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                 // 更新时间
	DeleteAt time.Time `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                 // 删除时间
	SysID    string    `gorm:"column:sys_id;comment:系统编号" json:"sys_id"`                       // 系统编号
	Key      string    `gorm:"column:key;comment:key" json:"key"`                              // key
	Value    string    `gorm:"column:value;comment:value" json:"value"`                        // value
}

// TableName SysConfig's table name
func (*SysConfig) TableName() string {
	return TableNameSysConfig
}
