// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysPolicy = "sys_policy"

// SysPolicy 描述各种升级策略
type SysPolicy struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"` // 数据id
	CreateAt     time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                 // 创建时间
	UpdateAt     time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                 // 更新时间
	DeleteAt     time.Time `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                 // 删除时间
	NodeID       string    `gorm:"column:node_id;comment:节点id" json:"node_id"`                     // 节点id
	SoftID       string    `gorm:"column:soft_id;comment:软件id" json:"soft_id"`                     // 软件id
	StartUpgrade time.Time `gorm:"column:start_upgrade;comment:开始升级时间" json:"start_upgrade"`       // 开始升级时间
	EndUpgrade   time.Time `gorm:"column:end_upgrade;comment:升级完成时间" json:"end_upgrade"`           // 升级完成时间
	UpgradeErr   string    `gorm:"column:upgrade_err;comment:升级错误" json:"upgrade_err"`             // 升级错误
}

// TableName SysPolicy's table name
func (*SysPolicy) TableName() string {
	return TableNameSysPolicy
}
