// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysDownload = "sys_download"

// SysDownload 记录软件的下载信息
type SysDownload struct {
	ID int32 `gorm:"column:id;primaryKey" json:"id"`
}

// TableName SysDownload's table name
func (*SysDownload) TableName() string {
	return TableNameSysDownload
}
