// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserOther = "user_other"

// UserOther 不同类别用户补充信息
type UserOther struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"` // 数据id
	CreateAt        time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                 // 创建时间
	UpdateAt        time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                 // 更新时间
	DeleteAt        time.Time `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                 // 删除时间
	UserID          int64     `gorm:"column:user_id;comment:用户id" json:"user_id"`                     // 用户id
	IDCard          string    `gorm:"column:id_card;comment:身份证号" json:"id_card"`                     // 身份证号
	Addr            string    `gorm:"column:addr;comment:地址" json:"addr"`                             // 地址
	BusinessLicense string    `gorm:"column:business_license;comment:营业执照" json:"business_license"`   // 营业执照
}

// TableName UserOther's table name
func (*UserOther) TableName() string {
	return TableNameUserOther
}
