// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserFee = "user_fee"

// UserFee 用户缴费充值有关记录信息
type UserFee struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"` // 数据id
	CreateAt        time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                 // 创建时间
	UpdateAt        time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                 // 更新时间
	DeleteAt        time.Time `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                 // 删除时间
	UserID          int64     `gorm:"column:user_id;comment:用户id" json:"user_id"`                     // 用户id
	OrderID         string    `gorm:"column:order_id;comment:订单id" json:"order_id"`                   // 订单id
	PayType         string    `gorm:"column:pay_type;comment:支付方式" json:"pay_type"`                   // 支付方式
	PayAmount       float64   `gorm:"column:pay_amount;comment:支付金额" json:"pay_amount"`               // 支付金额
	Currency        string    `gorm:"column:currency;comment:币种" json:"currency"`                     // 币种
	OppositeAccount string    `gorm:"column:opposite_account;comment:对方账户" json:"opposite_account"`   // 对方账户
	TradeType       string    `gorm:"column:trade_type;comment:交易类型(数据买卖 扩容等)" json:"trade_type"`     // 交易类型(数据买卖 扩容等)
}

// TableName UserFee's table name
func (*UserFee) TableName() string {
	return TableNameUserFee
}
