// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserPdc = "user_pdc"

// UserPdc 用户数据空间变化记录表
type UserPdc struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"` // 数据id
	CreateAt       time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                 // 创建时间
	UpdateAt       time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                 // 更新时间
	DeleteAt       time.Time `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                 // 删除时间
	UserID         int64     `gorm:"column:user_id;comment:用户id" json:"user_id"`                     // 用户id
	SpaceTotal     int32     `gorm:"column:space_total;comment:默认单位MB" json:"space_total"`           // 默认单位MB
	SpaceUse       float64   `gorm:"column:space_use;comment:使用空间单位字节" json:"space_use"`             // 使用空间单位字节
	SpaceAvailable float64   `gorm:"column:space_available;comment:剩余空间单位字节" json:"space_available"` // 剩余空间单位字节
	Status         string    `gorm:"column:status;comment:1正常 2禁用" json:"status"`                    // 1正常 2禁用
}

// TableName UserPdc's table name
func (*UserPdc) TableName() string {
	return TableNameUserPdc
}
