// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserLog = "user_log"

// UserLog 用户登录信息
type UserLog struct {
	ID       int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"` // 数据id
	CreateAt time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                 // 创建时间
	UpdateAt time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                 // 更新时间
	DeleteAt time.Time `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                 // 删除时间
	UserID   int64     `gorm:"column:user_id;comment:用户id" json:"user_id"`                     // 用户id
	LoginIP  string    `gorm:"column:login_ip;comment:登录ip" json:"login_ip"`                   // 登录ip
	Agent    string    `gorm:"column:agent;comment:登录代理" json:"agent"`                         // 登录代理
	Response string    `gorm:"column:response;comment:失败返回错误消息进行记录" json:"response"`           // 失败返回错误消息进行记录
}

// TableName UserLog's table name
func (*UserLog) TableName() string {
	return TableNameUserLog
}
