// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAppAllow = "app_allow"

// AppAllow 业务应用许可的服务项目和期限
type AppAllow struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:数据id" json:"id"` // 数据id
	CreateAt     time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                 // 创建时间
	UpdateAt     time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                 // 更新时间
	DeleteAt     time.Time `gorm:"column:delete_at;comment:删除时间" json:"delete_at"`                 // 删除时间
	AppID        int64     `gorm:"column:app_id;comment:应用id" json:"app_id"`                       // 应用id
	ServiceID    int32     `gorm:"column:service_id;comment:服务id" json:"service_id"`               // 服务id
	ServiceAllow time.Time `gorm:"column:service_allow;comment:服务许可时间" json:"service_allow"`       // 服务许可时间
	ServiceExp   time.Time `gorm:"column:service_exp;comment:服务过期时间" json:"service_exp"`           // 服务过期时间
	UseType      string    `gorm:"column:use_type;comment:使用方式(1次数 2流量 3期限)" json:"use_type"`      // 使用方式(1次数 2流量 3期限)
	Status       string    `gorm:"column:status;comment:1表示过期2禁用3正常4暂停" json:"status"`             // 1表示过期2禁用3正常4暂停
}

// TableName AppAllow's table name
func (*AppAllow) TableName() string {
	return TableNameAppAllow
}
